nginx:
    build: ./nginx
    ports:
        - "80:80"
    links:
        - load_balencer
    volumes:
      - ./front_end:/opt/app

rest_app:
    build: ./rest_app
    links:
        - postgres_host
        - redis_host
        - elasticsearch_test
    env_file:
      - ./docker-base.env
    ports:
      - 8080
    volumes:
      - ./rest_app:/opt/app

worker:
    build: ./rest_app/
    dockerfile: Dockerfile-worker
    links:
        - postgres_host
        - redis_host
        - elasticsearch
    env_file:
      - ./docker-base.env

postgres_host:
  image: postgres:9.4
  env_file:
    - ./docker-base.env
  volumes:
    - ./rest_app:/opt/app

redis_host:
    build: ./redis

load_balencer:
    image: dockercloud/haproxy
    ports:
      - 8081:80
    links:
      - rest_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

elasticsearch:
    image: elasticsearch
    ports:
        - 9200:9200

elasticsearch_test:
    image: elasticsearch
    ports:
        - 9222:9200
