nginx:
    build: ./nginx
    ports:
        - "80:80"
    links:
        - load_balencer
    volumes:
      - ./front_end:/opt/app

rest_app:
    build: ./rest_app
    links:
        - postgres_host
        - redis_host
    env_file:
      - ./docker-base.env
    ports:
      - 8080
    volumes:
      - ./rest_app:/opt/app

worker:
    build: ./rest_app/
    dockerfile: Dockerfile-worker
    links:
        - rest_app
        - redis_host

postgres_host:
  image: postgres:9.4
  ports:
    - "5433:5432"
  env_file:
    - ./docker-base.env
  volumes:
    - ./rest_app:/opt/app

redis_host:
    build: ./redis

load_balencer:
    image: dockercloud/haproxy
    ports:
      - 8081:80
    links:
      - rest_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
