# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, verbose_name='Modelo')),
                ('color', models.CharField(choices=[('azul', 'Azul'), ('preto', 'Preto'), ('prata', 'Prata'), ('vermelho', 'Vermelho'), ('Verde', 'Verde'), ('outro', 'Outro')], max_length=16, verbose_name='Cor')),
                ('category', models.CharField(choices=[('moto', 'Moto'), ('carro', 'carro')], max_length=16, verbose_name='Tipo')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Manufacturer', verbose_name='Fabricante')),
            ],
        ),
    ]
